view_title = Nieuwsberichten
add = Een nieuwbericht toevoegen
edit = Dit nieuwsbericht aanpassen
delete = Dit nieuwsbericht verwijderen

type = Soort weergave
type_overview = Overzicht van nieuwsberichten
type_list = Lijst van titels
type_article = Meeste recente artikel volledig

inline = Volledige artikels in huidige blok weergeven

item_count = Max. aantal getoonde berichten
load_more = Knop om meer berichten in te laden


