view_title = Polls

no_polls = Er zijn geen polls beschikbaar.

action_add = Een poll toevoegen
action_edit = Deze poll aanpassen
action_delete = Deze poll verwijderen

view_type = Type weergave
view_type_list = Lijstweergave van alle polls
view_type_last_active = Meest recent, actieve poll

options = Opties (een optie per regel)

active = Actief
inactive = Inactief

warning_delete = Weet je zeker dat je deze poll wilt verwijderen? De poll wordt definitief verwijderd.
