view_title = Polls

no_polls = There's no poll available.

action_add = Add a poll
action_edit = Update this poll
action_delete = Delete this poll

view_type = View type
view_type_list = Overview of all polls
view_type_last_active = Most recent, active poll

options = Options (one option per line)

active = Active
inactive = Inactive

warning_delete = Are you sure you want to permanently delete this poll?
