#!/usr/bin/env ruby

## Minifies JS and CSS files

require 'yui/compressor'
require 'sass'

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../'))
Dir.chdir(File.expand_path(File.dirname(__FILE__) + '/../'))

def find_files(path)
	Dir.foreach("#{path}") { |name|
		@js_files.push("#{path}/#{name}") if (name.end_with?('.js')) && (!name.end_with?('.min.js'))
		@css_files.push("#{path}/#{name}") if (name.end_with?('.css')) && (!name.end_with?('.min.css'))
		@scss_files.push("#{path}/#{name}") if (name.end_with?('.scss'))
		find_files("#{path}/#{name}") if ((File.directory?("#{path}/#{name}")) &&
			(name != '.') && (name != '..') && (name != 'ext') &&
			(!File.symlink?("#{path}/#{name}")) &&
			("#{path}/#{name}" != 'lib/mojura/webapp/mojura/js/sources') &&
			("#{path}/#{name}" != 'lib/mojura/webapp/ext'))

	}
end


## Find all files in views and ext and create a minified file for each of them
@js_files = []
@css_files = []
@scss_files = []

if ARGV.length > 0
	ARGV.each { | file_name |
		@js_files.push("#{path}/#{name}") if (name.end_with?('.js')) && (!name.end_with?('.min.js'))
		@css_files.push("#{path}/#{name}") if (name.end_with?('.css')) && (!name.end_with?('.min.css'))
		@scss_files.push("#{path}/#{name}") if (name.end_with?('.scss'))
	}
else
	find_files('lib/mojura/webapp')
end

compressor = YUI::JavaScriptCompressor.new
@js_files.each { |original|
	minified = original.gsub(/\.js$/, '.min.js')
	File.write(minified, compressor.compress(File.read(original)))
	STDOUT << "Created file #{minified}\n"
}

compressor = YUI::CssCompressor.new
@css_files.each { |original|
	minified = original.gsub(/\.css$/, '.min.css')
	File.write(minified, compressor.compress(File.read(original)))
	STDOUT << "Created file #{minified}\n"
}

@scss_files.each { |original|
	minified = original.gsub(/\.scss$/, '.min.css')
	Sass.compile_file(original, minified, :style => :compact)
	STDOUT << "Created file #{minified}\n"
}