#!/usr/bin/env ruby

## Deletes all minified files if an original file exists

require "json"

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../'))
Dir.chdir(File.expand_path(File.dirname(__FILE__) + '/../'))

@js_files = []
@css_files = []

def find_files(path)
	Dir.foreach("#{path}") { |name|
		@js_files.push("#{path}/#{name}") if (name.end_with?('.min.js'))
		@css_files.push("#{path}/#{name}") if (name.end_with?('.min.css'))
		find_files("#{path}/#{name}") if ((File.directory?("#{path}/#{name}")) &&
			(name != '.') && (name != '..') &&
			(!File.symlink?("#{path}/#{name}")))
	}
end

find_files("webapp")

@js_files.each { | minified |
	original = minified.gsub(/\.min\.js$/, '.js')
	if (File.exist?(original))
		File.delete(minified) if (File.exist?(original))
		STDOUT << "Deleted #{minified}\n"
	end
}

