#!/usr/bin/env ruby

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../'))
Dir.chdir(File.expand_path(File.dirname(__FILE__) + '/../'))

require 'rack'
require 'api/lib/api'
require 'webapp/mojura/lib/webapp'

env = {'rack.session' => {}, 'rack.request.cookie_hash' => {}}
MojuraAPI::API.load
MojuraAPI::API.init_thread(env)

objects = MojuraAPI.constants.select { |c|
	klass = MojuraAPI.const_get(c)
	(Class === klass) && (klass.ancestors.include?(MojuraAPI::DbObject)) && (klass.name != 'MojuraAPI::DbObject')
}

objects.each { |c|
	obj = MojuraAPI.const_get(c).new
	STDOUT << "-----------------\n#{c}\n"
	STDOUT << JSON.pretty_generate(obj.fields) + "\n\n"
}

