#!/usr/bin/env ruby

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../'))
Dir.chdir(File.expand_path(File.dirname(__FILE__) + '/../'))

require 'json'
require 'rack'
require 'api/lib/api'
require 'webapp/mojura/lib/webapp'

type = ARGV[0] || 'web'
command = ARGV[1] || ''

command, params = command.split('?', 2)
command ||= ''
params ||= ''
params = Rack::Utils.parse_query(params)
params.symbolize_keys!

STDOUT << "Command: #{command}\nParams: #{params.to_s}\n"

env = {'rack.session' => {}, 'rack.request.cookie_hash' => {}}
MojuraAPI::API.load
MojuraAPI::API.init_thread(env)

if type == 'api'
	result = MojuraAPI::API.call(command, params, (params[:_method] || 'get'))
else
	result = MojuraWebApp::WebApp.render(command, params)
end

STDOUT << "#{result}"
STDOUT << "\n"
