#!/usr/bin/env ruby

require 'fileutils'

## TODO Document

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../'))
Dir.chdir(File.expand_path(File.dirname(__FILE__) + '/../'))

@view = ARGV[0] || ''
@view_path = "webapp/views/#{@view}"

unless File.exists?(@view_path)
	STDOUT << "The view #{@view_path} does not exist.\n"
	exit(1)
end

unless File.symlink?(@view_path)
	STDOUT << "The view is a custom view which can not be removed. Only symlinked views van be disabled.\n"
	exit(2)
end

File.delete(@view_path)
STDOUT << "view #{@view} is disabled.\n"