view_title = Kaarten
add = Een locatie toevoegen
edit = Deze locatie aanpassen
delete = Deze locatie verwijderen

warning_delete = Weet je zeker dat je deze locatie definitief wilt verwijderen?

address = Adres of andere zoekterm
address_not_found = Het opgegeven adres is niet gevonden.

zoom = Zoomfactor
zoom_auto = Automatisch inzoomen
zoom_min = Niet inzoomen
zoom_max = Inzoomen op straatniveau
